apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: default-profile
  labels:
    controller-tools.k8s.io: "1.0"
  name: fashion-mnist-cell-tuner
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: --cells_number
      parameterType: int
      feasibleSpace:
        min: "10"
        max: "200"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: gcr.io/velascoluis-test/katib_exp
                  command:
                  - "python"
                  - "/katib_exp/experiment_katib.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never